(function(c,i){c.execute(function(){c.when("generic-observable").register("gw-herotator-controller",function(c){var e=function(){};return function(m){function h(){g.notifyObservers("delayBegin")}function f(){g.notifyObservers("delayInterrupted")}function b(a){for(var g=0;g<w.length;g++)if(w[g]===a)return g+1}function l(a){a=a||{};return{delay_complete:a.delay_complete||e,js_ready:a.js_ready||e,fg_loaded:a.fg_loaded||e,mouse_move:a.mouse_move||e,mouse_leave:a.mouse_leave||e,delay_interrupted_timeout:a.delay_interrupted_timeout||
e,rotation_complete:a.rotation_complete||e,goto_card:function(a){a!==x&&j.user_navigation(w[a-1])},user_navigation:a.user_navigation||function(a){j=new t(a)},user_interaction:a.user_interaction||function(){j.user_navigation(w[x-1])},stop_autorotation:a.stop_autorotation||function(){j.user_navigation(w[x-1])},pause:a.pause||e,resume:a.resume||e}}function d(){function a(){!b&&A[g]&&(j=k===1?new p:new s)}h();var g=w[(x-1+1)%k+1-1],b=!0;return new l({fg_loaded:function(b){b===g&&a()},delay_complete:function(){b=
!1;a()},mouse_move:function(){j=new i},pause:function(){j=new n}})}function i(){f();return new l({mouse_move:f,mouse_leave:function(){j=new d},delay_interrupted_timeout:function(){j.mouse_leave()},pause:function(){j=new n(!0)}})}function n(a){f();return new l({mouse_move:function(){a=!0;f()},mouse_leave:function(){a=!1},resume:function(){j=a?new i:B>0?new d:new p}})}function s(){g.notifyObservers("autorotating");x=(x-1+1)%k+1;g.notifyObservers("gotoCard",x);B--;return new l({rotation_complete:function(){j=
B>0?new d:new p},mouse_move:function(){j=B>0?new q:new p},pause:function(){j=new a}})}function q(){var a=!1;return new l({rotation_complete:function(){h();j=a?new n:new i},pause:function(){a=!0},resume:function(){a=!1}})}function a(){var a=!1;return new l({rotation_complete:function(){h();j=new n(a)},mouse_move:function(){a=!0},mouse_leave:function(){a=!1}})}function t(a){g.notifyObservers("userNavigation");x=b(a);g.notifyObservers("gotoCard",x);return new l({rotation_complete:function(){j=new p},
user_navigation:function(a){j=new o(a)},user_interaction:e})}function o(a){return new l({rotation_complete:function(){j=new t(a)},user_navigation:function(g){a=g},user_interaction:e})}function p(){g.notifyObservers("stopAutorotation");return new l({})}var m=m||{},g=new c,j=new function(){function a(){A[C]&&b&&(g.notifyObservers("ready"),j=new d,k&&j.pause(),f&&j.stop_autorotation())}var b=!1,f=!1,k=!1;return new l({fg_loaded:function(g){g===C&&a()},js_ready:function(){b=!0;a()},user_navigation:e,
stop_autorotation:function(){f=!0},pause:function(){k=!0},resume:function(){k=!1}})},w=m.fgIDs||[],k=w.length,C=w[0],x=m.card_num||1,A={},B=m.circular?Infinity:k;return{delayComplete:function(){j.delay_complete()},jsReady:function(){j.js_ready()},fgLoaded:function(a){A[a]=!0;C===a&&g.notifyObservers("atfLoaded");j.fg_loaded(a)},mouseMove:function(){j.mouse_move()},mouseLeave:function(){j.mouse_leave()},delayInterruptedTimeout:function(){j.delay_interrupted_timeout()},rotationComplete:function(){j.rotation_complete()},
gotoCard:function(a){j.goto_card(a)},userInteraction:function(){j.user_interaction()},userNavigation:function(a){j.user_navigation(a)},stopAutorotation:function(){j.stop_autorotation()},pause:function(){j.pause()},resume:function(){j.resume()},addObserver:g.addObserver,removeObserver:g.removeObserver}}});c.when("herotator-btf").register("herotator",function(c){return c});c.register("herotator-btf",function(){return function(z,e){function m(a){return function(){c.when("gw-desktop-herotator/controller").execute(function(){u[a]()})}}
function h(a,g,b){a.addEventListener?a.addEventListener(g,b,!1):a.attachEvent("on"+g,b)}function f(a,b){g[a]=[];var d=b.length;if(d>0)for(var f=0;f<d;f++)(function(d){var f=new Image;f.onload=function(){g[a].splice(q(g[a],f),1);g[a]&&g[a].length===0&&c.when("gw-desktop-herotator/controller").execute(function(){var g=document.getElementById("gw-ftGr-"+a),b=g.className,b=b.replace(/\s*\ba\-lazy\-loaded\b\s*/,"");g.className=b;u.fgLoaded(a)});c.when("A").execute(function(g){var b=g.$("#gw-ftGr-"+a+" img.a-dynamic-image");
g.loadDynamicImage(b)})};g[a].push(f);f.src=b[d].src})(f);else c.when("gw-desktop-herotator/controller").execute(function(){u.fgLoaded(a)})}function b(){p=Date.now()}function l(){k||n()}function d(){x=x?Math.min(x,Date.now()):Date.now();clearTimeout(t.timeout_id);clearTimeout(d.timeout_id);d.timeout_id=setTimeout(function(){d.timeout_id=0;u.delayInterruptedTimeout()},3E3)}function r(){k=!0}function n(){if(!n.sent)clearTimeout(n.timeout),n.timeout=setTimeout(function(){s(z.uri,z.data);n.sent=!0},2E3)}
function s(a,g){c.when("A").execute(function(b){b.$.ajax(a,{async:!1,cache:!1,type:"post",data:g})})}function q(a,g){if(a.indexOf)return a.indexOf(g);for(var b=0;b<a.length;b++)if(a[b]===g)return b}function a(){B("#gw-desktop-herotator").addClass("gw-desktop-herotator-ready");c.register("herotator-controls",function(){var a=B("#gw-desktop-herotator-controls"),g=a.find("a");g.length>1?(g.click(function(a){a.preventDefault();(a=B(this).attr("href").match(/^\#gw-ftGr-(\w+-hero-[\w\d\-]+)/))&&u.userNavigation(a[1])}),
g.each(function(){var a=B(B(this).attr("href")),g=a.find(".gw-ftGr-desktop-hero-alt").text();(g=g||a.find(".image-map.shogun-widget img").attr("alt"))&&B(this).find(".gw-text").text(g)}),a.find("li").fadeIn(800),i.GWI&&i.GWI.recordLatency("gwHerotatorActive")):a.hide();return{controls:a,links:g}})}function t(){C<x&&(w-=x-C,x=0);C=Date.now();t.timeout_id=setTimeout(function(){w=j;u.delayComplete()},w)}function o(a,g){if(o.current_card!==g)o.current_card=g,A.gotoPage(g),B("#gw-desktop-herotator-controls li a").removeClass("active"),
B("#gw-desktop-herotator-controls li a.herotator-goToPage-"+g).addClass("active"),F.notifyObservers("page_changed");setTimeout(function(){u.rotationComplete()},250)}var p=Date.now(),g={},j=5E3,w=j,k=!1,C=0,x=0,A,B,D=document.getElementById("gw-desktop-herotator").getElementsByTagName("ol")[0],F,u;h(D,"click",m("userInteraction"));h(D,"mouseenter",m("mouseMove"));h(D,"mousemove",m("mouseMove"));h(D,"mouseleave",m("mouseLeave"));h(D,"touchstart",m("userInteraction"));h(D,"touchmove",m("userInteraction"));
h(D,"touchend",m("userInteraction"));h(D,"touchcancel",m("userInteraction"));for(var D=document.getElementById("gw-desktop-herotator").getElementsByTagName("li")[0],y=0,v=D.childNodes[y];v&&String(v.nodeName).toLowerCase()!=="div";)y++,v=D.childNodes[y];y=v;D=String(y.id).replace(/^gw-ftGr-/,"");y=y.getElementsByTagName("img");f(D,y||[]);for(var E=[D],D=0;e[D];)E.push(e[D].fgID),D++;c.when("gw-herotator-controller").execute(function(g){u=new g({fgIDs:E});u.addObserver("atfLoaded",b);u.addObserver("delayBegin",
t);u.addObserver("delayInterrupted",d);u.addObserver("gotoCard",o);u.addObserver("userNavigation",l);u.addObserver("stopAutorotation",r);u.addObserver("ready",function(){var g=Date.now()-p;w=Math.max(j-g,1);a();B("#gw-desktop-herotator").addClass("gw-desktop-herotator-ready")});c.register("gw-desktop-herotator/controller");c.when("generic-observable").register("gw-desktop-herotator",function(a){F=new a;return{getAutorotationDelay:function(){return j},setAutorotationDelay:function(a){a=parseInt(a,
10);w=a-(j-w);j=a},stopAutorotation:function(){u.stopAutorotation()},disableNavigation:function(){B("#gw-desktop-herotator-controls").hide();A.pause()},enableNavigation:function(){B("#gw-desktop-herotator-controls").show();A.resume()},pause:function(){u.pause()},resume:function(){u.resume()},addObserver:F.addObserver,removeObserver:F.removeObserver}})});c.when("A","a-carousel-framework","gwAjax").execute(function(a,g,b){function d(){for(var a=0;e[a];){var g=e[a].fgID,b=e[a].content,k=document.getElementById("gw-ftGr-"+
g);B(k).html(b);b=k.getElementsByTagName("img");f(g,b);a++}}B=a.$;g.onInit("gateway-desktop-layout.herotator",function(){var f=a.$("#gw-desktop-herotator > .a-carousel-container");A=g.getCarousel(f);A.onChange("pageNumber",function(){var a=A.getAttr("pageNumber");u.gotoCard(a);a-=2;e[a]&&e[a].callbackUrl&&(b(e[a].callbackUrl,{type:"POST",id:"desktop-herotator-btf-"+e[a].fgID}),delete e[a].callbackUrl)});d();c.when("gw-desktop-herotator").register("gw-desktop-herotator/dom-ready");c.when("gw-desktop-herotator/controller",
"gw-desktop-herotator").execute(function(){u.jsReady()})})})}})})})(function(){var c=window.AmazonUIPageJS||window.P,i=c._namespace||c.attributeErrors;return i?i("AmazonGatewayHerotatorJS"):c}(),window);